# Project HomePage: https://github.com/alecthw/chnlist

mode: rule
log-level: info

http:
  url-rewrite:
    - ^(http|https):\/\/(www.)?(g|google)\.cn https://www.google.com 302

  script:

  force-http-engine:
    - "*:80"
    - "*:4480"
    - "*:9102"

  mitm:
    - "example.cc"
  ca-passphrase: "123456"
  ca: "MIIJkQIBAzCCCVcGCSqGSIb3DQEHAaCCCUgEgglEMIIJQDCCA/cGCSqGSIb3DQEHBqCCA+gwggPkAgEAMIID3QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIaTx/QiMcDjICAggAgIIDsOJNrb28uLH4xTNxYlvG+FIZtixO0jz7SKs5f4WC59va98uumEgNPUMBIP2SUjCgVJzIJfcXaENgEP/RiMpypjbI81jVTREiZVkiORCyG8eVPgahSWB0LqECcCGsCAqjRvuE8fq/W1a5WtvBRsm2FBk9d46xgB+U353VBBOqLk+A1TQhi95Vh8B46Jh2vp2mRbZFgWAYleeuB/HGCwIuL7j3kk6OI9EB86ik9HbD6TfHi1rBifiE7qamKEWmlk5EqeJY2Vz++y7f1IeJApRWhny+hzBqRQJXF9xuqgUGrDwFK5y1rN80rPZfWhcdr44+CaWFJbzsFFq/41JoV3USpcSKHY7anXLfogjYjJ05vroI4zRprtxvtLfl/tIi9KvKO39079YMWsaSi0BqEJ0ygPCVQY7epSTg4yJ6rgkyV9p6/vn07q87NOwOIzBxN3geEOOphfTF+CHf54AnaPNyf9f+u8+zMMNoz/NvfIcHFSVW3ciNFSI9P9nbJjw4Zz3447vpxlIMTP1pQSehhUKTNgY51Mosyvw9DDiriE7rFRNCAbXr3v3lD8aLHFrXESlH/20BN671VM56aN26elzK0eyTxAn29l+ba+D2Lp5vT/ve3XfHXrMO5FXQFT+lr8ZcnGKPfnNk30Wd1+ID3tt5O6FaS3f2rKZHyX7I/3WefrgIZ4zhsFnCOzghMmyJgMym5ay58+cTffcCeGzofWjm8j4oO5a7jW6Pv9Bwt7Hx9aM/Dd0d9GNLrCJ+nHP2aXV+lulYtl8FDQL5Cz10j5E/rg/SRHcgO+93qtmdI3+YP+WCIPqCukquye5bKoo2oiiGjdELegz/1AZcxb6N++iqmAYN4T4jm9eKhpEmLOqwZFP4rK2yUGFkvS2gdDgTlWg+Lpziuw2mkdg4hAq9Vzl0nmeoOIJzRzxLQBdvmZXbCVvOu/uFiUfAhjP56LDNpG6+AP1c87TQHH1knbAH8hVY+ju8kTRSKtvz2ZU4qSf5QEN1sKDgRlFIdgLJj/9lv5ycz1mM0fZt0wGy3oZGB2LhWnMC2Yr6YayQ4LvUJBKEmsMant2bHcuoaCy/grAmT1c8cSSYnChh3kZnxGx4IuPGyF8wnRJNLNFGkYNQPGXBEJCQ9Z0rQBU6SNo1C2A3NTzs0vuJ0I/6+zxufWgawGGtla38+0vRV7nfuguRsh7qc5R/GjsSO5Twc7ODAThTczCQm540bC65y0CWLbJLe+//qUKYHAQQpv4WBf8uNmXdwvcKMIIFQQYJKoZIhvcNAQcBoIIFMgSCBS4wggUqMIIFJgYLKoZIhvcNAQwKAQKgggTuMIIE6jAcBgoqhkiG9w0BDAEDMA4ECMRJsgBVcGv4AgIIAASCBMgQoKbdgOToJraEUqStzlOsYfEZDr2jkahPhAc+5zTdEaXRMN9J82IwVEHrWxua38ckyHQgeT2ET64r/c2VUIbUTPN53WWERJIEhDEcLGtH1lEN2rao4cGAugFWu+EIjJRk0bsCTqTFsIQ3oZLZZfZIUeP1BKLgpru2qzsobxuEMjylwKIsOD8YogHbWB/i6FnnCetmKeo0UoKknMK3obIMPg0U89t/cmUfs03v+8rTlQkvYeppIp20YzsFFqyaHxpDMu+Yegv5ETAEzKQMVJAN9WPNwXpT7XdH+Yb+ItDZuAwy2f9oX2BgOaHB3NjqAxyCzq+uyQdZFRvlfpKJppDQibB27I59lkfyTu6xiMYkE8ITHjxZ1MN5m1GGpB7zFmJQY4EU0ZmzuHNa0XSJeoZdKFUPCZRO3V7rlVlfM/wg20yHC1F+4PpZMqrcH/tpw2TCR8HMPB1ClXg/cD3LeF+EwyWrevzLvNyNLg9vItmeiRQ3Izz9Hmq9ravtPSCFg5dt8Snxs2YnkohkX+uU8ItE91FbY9U0Uu1zuIknpO+jO8wELGegOBIdxrZ6gEM3a0+zq+TrnOuziFlMnPqxdlQsvmIrScLxVBr2tOmow9tqHA1IWFGhLG3hLTfmcoI5Ps8RD1yqemFh1QaDSWPSWY7yLjeC2be+ufp7LnLrfam2VYI6op0pXh8ZIFRaLjsclaMDfyNGrJSKBxyE68HGILOBAPyONTZJeiJ7aZniCVK/XsVLfGInm20rv/d6sfPg94dlRVPh3jbLMmx9hb9VCwO9gFR9Ixoov1lreGlKhzsb3PJLzOpBZAk2MhKLaok/euTBBJlao+iifjb5yMR1U8IlslZrHxEKgq5Md89fgFT/wOEjeHEuV09L8WCokdTIhfWYr9Ap1raDoZV9FNQT3EWQRq53nIpIC5ZsXGyfpB3wJVSOkHKvw2fWmY5ucZOKZB3B2tUjqqlDYZTv2COHMUp2+T2yU5kbFSNJ3cRIOIct7Ujxlq74OvGDfzq9A6X/wET8xsrpgGwXGvsghpta6sp8LE+dANupKNEa3rrQluQAzaZP3lnsHSHrP+aBzkpl3dCGTUK7hkIvnzyPRGMjiwpMY/bSTATIFM8GUdeoAqxE/LdTw9FEVFMwTGbdERz57VzVxb/6E2RiQL/tKQkAYHjwWJSbxMjOP/Ypup6Olz4fnBJqIVYDJt68t+5VUDn91KDPmGPztrcfNW7Etv8wd4LA2KhWZolMeH/6GvNaanFwjDVNQAGOb0KNGN9zXxa2iU2EyoOCWH/RiKbdM2d7GYzqYAkVMpFNtYjLfpI/mIMSlT+CBevaW3E5U6q79edAKWf+zTwg/HotTFuOfB1X2MdETTUNlWlsU9KBMPJibJFYmacrhTZRiuiombgu2rM4neeZfv3EAyOC4Ekt7f8ignRJb95sY6NxNH3ts84VR2ixOMli94CGUmfP8AHuxFh08Xh5pAtsfMEHxvIZx2GrlwUlzy9shZeZieSOO59VSUqJs34C5dfoU0MOlX5Ig84P/392cS4gujIwWIjHzq4+HtP1mIVmn0PbE2IfPpxp7C9Y36q8VBATcTPZu4GDswLcFt1+Yw+aihWtmWefAWPsW0wZY3G6rlPc05IxJTAjBgkqhkiG9w0BCRUxFgQU0Rmz6oJhNgCH6QhLbf3NeGQ5QxUwMTAhMAkGBSsOAwIaBQAEFI6VFMdX6IdD5TS65ZAYg+UvgjnwBAg/2Y1WMXZEQQICCAA="

dns:
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - tls://223.5.5.5
    - tls://120.53.53.53
  fake-ip-filter:
    - "*.jsdelivr.net"
    - "ghproxy.com"
    - "ghproxy.net"

proxy-providers:
  Subscribe:
    url: https://raw.githubusercontent.com/alecthw/chnlist/main/config/Node/stash
    filter: ^(?!.*(Direct|Ad-))
    interval: 86400

proxy-groups:
  - name: Proxy
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Rocket.png
    type: select
    proxies:
      - DIRECT
      - Fallback
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡¬ğŸ‡§ UK
      - ğŸ‡°ğŸ‡· KR
      - ğŸ‡®ğŸ‡³ IN
      - ğŸ‡ºğŸ‡³ Special
      - ğŸ›« Airport
    filter: .*
  - name: Domestic
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Direct.png
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: AdBlock
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Advertising.png
    type: select
    proxies:
      - REJECT
      - Domestic
      - Proxy

  # Auto
  - name: Fallback
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Auto.png
    type: fallback
    proxies:
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡ºğŸ‡¸ US
    url: http://cp.cloudflare.com/generate_204
    interval: 300

  # Apple service
  - name: AppleGlobal
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Apple.png
    type: select
    proxies:
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡¨ğŸ‡³ TW
      - Proxy

  # Media
  - name: DisneyPlus
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Disney%2B.png
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - Proxy
  - name: Netflix
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Netflix.png
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - Proxy
  - name: Spotify
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Spotify.png
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡®ğŸ‡³ IN
      - Proxy
  - name: GlobalMedia
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/GlobalMedia.png
    type: select
    proxies:
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡¨ğŸ‡³ TW
      - Proxy

  # Other
  - name: Telegram
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Telegram.png
    type: select
    proxies:
      - Proxy
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
  - name: Speedtest
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Speedtest.png
    type: select
    proxies:
      - Domestic
      - Proxy
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
  - name: PayPal
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/PayPal.png
    type: select
    proxies:
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡¨ğŸ‡³ TW
      - Proxy
      - Domestic
  - name: OpenAI
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Bot.png
    type: select
    proxies:
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡ºğŸ‡³ Special
  - name: Steam
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Game.png
    type: select
    proxies:
      - Domestic
      - Proxy
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡ºğŸ‡³ Special
  - name: Epic
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Game.png
    type: select
    proxies:
      - Domestic
      - Proxy
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡ºğŸ‡³ Special
  - name: Ubisoft
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Game.png
    type: select
    proxies:
      - Domestic
      - Proxy
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡ºğŸ‡³ Special
  - name: Xbox
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Game.png
    type: select
    proxies:
      - Domestic
      - Proxy
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡°ğŸ‡· KR
      - ğŸ‡ºğŸ‡³ Special
  - name: Microsoft
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Microsoft.png
    type: select
    proxies:
      - Domestic
      - Proxy
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡¸ US
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡°ğŸ‡· KR
      - ğŸ‡ºğŸ‡³ Special

  # Final
  - name: Final
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Final.png
    type: select
    proxies:
      - Proxy
      - Domestic

  # Area
  - name: ğŸ‡­ğŸ‡° HK
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/HK.png
    type: select
    include-all: true
    filter: (?i)(æ¸¯|HK|Hong)

  - name: ğŸ‡¸ğŸ‡¬ SG
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/SG.png
    type: select
    include-all: true
    filter: (?i)(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)

  - name: ğŸ‡¯ğŸ‡µ JP
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/JP.png
    type: select
    include-all: true
    filter: (?i)((\bæ—¥((?!ç”¨).)+)|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan)

  - name: ğŸ‡ºğŸ‡¸ US
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/US.png
    type: select
    include-all: true
    filter: (?i)(\bç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|\bUS|(United States))

  - name: ğŸ‡¨ğŸ‡³ TW
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/TW.png
    type: select
    include-all: true
    filter: (?i)(å°|æ–°åŒ—|å½°åŒ–|TW|Tai)

  - name: ğŸ‡¬ğŸ‡§ UK
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/UK.png
    type: select
    include-all: true
    filter: (?i)(è‹±å›½|UK|ä¼¦æ•¦|(United Kingdom)|GBR)
  - name: ğŸ‡°ğŸ‡· KR
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/KR.png
    type: select
    include-all: true
    filter: (?i)(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)
  - name: ğŸ‡®ğŸ‡³ IN
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/IN.png
    type: select
    include-all: true
    filter: (?i)(å°åº¦|å­Ÿä¹°|æ–°å¾·é‡Œ|ç­åŠ ç½—å°”|India)

  - name: ğŸ‡ºğŸ‡³ Special
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/UN.png
    type: select
    include-all: true
    filter: ^(?i)(?!.*(æ¸¯|HK|Hong|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|(\bæ—¥((?!ç”¨).)+)|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan|\bç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|\bUS|(United States)|å°|æ–°åŒ—|å½°åŒ–|TW|Tai|è‹±å›½|UK|ä¼¦æ•¦|(United Kingdom)|GBR|KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“|å°åº¦|å­Ÿä¹°|æ–°å¾·é‡Œ|ç­åŠ ç½—å°”|India))

  - name: ğŸ›« Airport
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Airport.png
    type: select
    include-all: true

rules:
  - RULE-SET,Lan,DIRECT
  - RULE-SET,CustomDirect,Domestic
  - RULE-SET,CustomProxy,Proxy
  - RULE-SET,Direct,Domestic
  - RULE-SET,CustomReject,AdBlock
  - RULE-SET,AdvertisingLite,AdBlock
  - RULE-SET,AdvertisingLite_Domain,AdBlock
  - RULE-SET,ZhihuAds,AdBlock
  - RULE-SET,ChinaMedia,Domestic
  - RULE-SET,AppleTV,AppleGlobal
  - RULE-SET,Disney,DisneyPlus
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Spotify,Spotify
  - RULE-SET,GlobalMedia,GlobalMedia
  - RULE-SET,GlobalMedia_Domain,GlobalMedia
  - RULE-SET,Download,Domestic
  - RULE-SET,GameDownloadCN,Domestic
  - RULE-SET,GameDownload,Domestic
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,PayPal,PayPal
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Steam,Steam
  - RULE-SET,Epic,Epic
  - RULE-SET,UBI,Ubisoft
  - RULE-SET,Ubisoft,Ubisoft
  - RULE-SET,Xbox,Xbox
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,ProxyLite,Proxy
  - RULE-SET,China,Domestic
  - GEOIP,CN,Domestic
  - MATCH,Final

rule-providers:
  Lan:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
    interval: 43200
  CustomDirect:
    behavior: classical
    url: https://raw.githubusercontent.com/alecthw/chnlist/release/Providers/Custom/CustomDirect.yaml
    interval: 43200
  CustomProxy:
    behavior: classical
    url: https://raw.githubusercontent.com/alecthw/chnlist/release/Providers/Custom/CustomProxy.yaml
    interval: 43200
  Direct:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
    interval: 43200
  CustomReject:
    behavior: classical
    url: https://raw.githubusercontent.com/alecthw/chnlist/release/Providers/Custom/CustomReject.yaml
    interval: 43200
  AdvertisingLite:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.yaml
    interval: 43200
  AdvertisingLite_Domain:
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.yaml
    interval: 43200
  ZhihuAds:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ZhihuAds/ZhihuAds.yaml
    interval: 43200
  ChinaMedia:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml
    interval: 43200
  AppleTV:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml
    interval: 43200
  Disney:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
    interval: 43200
  Netflix:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
    interval: 43200
  Spotify:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
    interval: 43200
  GlobalMedia:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml
    interval: 43200
  GlobalMedia_Domain:
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml
    interval: 43200
  Download:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml
    interval: 43200
  GameDownloadCN:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.yaml
    interval: 43200
  GameDownload:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.yaml
    interval: 43200
  Telegram:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    interval: 43200
  Speedtest:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
    interval: 43200
  PayPal:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml
    interval: 43200
  OpenAI:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
    interval: 43200
  Steam:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    interval: 43200
  Epic:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml
    interval: 43200
  UBI:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.yaml
    interval: 43200
  Ubisoft:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Ubisoft/Ubisoft.yaml
    interval: 43200
  Xbox:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xbox/Xbox.yaml
    interval: 43200
  Microsoft:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    interval: 43200
  ProxyLite:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.yaml
    interval: 43200
  China:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml
    interval: 43200


# BoxJS, http://boxjs.com
# https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.stash.stoverride

# Common
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Stash/Redirect/Redirect.stoverride

# Ads Filter
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/AdvertisingLite/AdvertisingLite.sgmodule
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Stash/AdvertisingLite/AdvertisingLite.stoverride
# https://raw.githubusercontent.com/app2smile/rules/master/module/bilibili.stoverride
# https://raw.githubusercontent.com/app2smile/rules/master/module/tieba.stoverride

# Apple App unlock
# https://raw.githubusercontent.com/VirgilClyne/iRingo/main/stoverride/TestFlight.stoverride

# Other app unlock
# https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/KuWoMusic/KuWoMusic.Stash.stoverride
# https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/Nicegram/Stash.stoverride
# https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/WPSOffice/Stash.stoverride
# https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/Xmind/Xmind.Stash.stoverride
# https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.stoverride